from __future__ import annotations

import os
from collections.abc import Iterable

import pandas as pd
from arfpy.arf import arf as ARFEngine
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

from katabatic.models.base_model import Model

from .utils import (
    load_split_dataset,
    prepare_arf_dataframe,
    set_seed,
    split_synthetic,
)


class ARF(Model):
    def __init__(
        self,
        num_trees: int = 30,
        max_iters: int = 10,
        delta: float = 0.0,
        min_node_size: int = 5,
        early_stop: bool = True,
        verbose: bool = True,
        seed: int = 42,
        n_jobs: int = -1,
    ) -> None:
        super().__init__()

        self.num_trees = num_trees
        self.max_iters = max_iters
        self.delta = delta
        self.min_node_size = min_node_size
        self.early_stop = early_stop
        self.verbose = verbose
        self.seed = seed
        self.n_jobs = n_jobs

        self._arf = None
        self._target_col: str | None = None
        self._columns: list[str] = []
        self._categorical_cols: list[str] = []
        self._train_size = 0

    @classmethod
    def get_required_dependencies(cls) -> list[str]:
        return [
            "arfpy",
            "sklearn",
            "numpy",
            "pandas",
            "scipy",
        ]

    def fit(
        self,
        x: pd.DataFrame,
        y: pd.Series,
        categorical_cols: Iterable[str] | None = None,
        seed: int | None = None,
        verbose: bool | None = None,
    ) -> ARF:
        if seed is not None:
            self.seed = int(seed)

        if verbose is not None:
            self.verbose = bool(verbose)

        set_seed(self.seed)

        train_df, target_col, categorical = (
            prepare_arf_dataframe(
                x,
                y,
                categorical_cols,
            )
        )

        self._target_col = target_col
        self._columns = train_df.columns.tolist()
        self._categorical_cols = categorical + [
            target_col
        ]
        self._train_size = len(train_df)

        self._arf = ARFEngine(
            x=train_df,
            num_trees=self.num_trees,
            delta=self.delta,
            max_iters=self.max_iters,
            early_stop=self.early_stop,
            verbose=self.verbose,
            min_node_size=self.min_node_size,
            random_state=self.seed,
            n_jobs=self.n_jobs,
        )

        # Density estimation stage required before FORGE.
        self._arf.forde()

        self.is_fitted = True

        return self

    def sample(
        self,
        size: int | None = None,
        verbose: bool | None = None,
        seed: int | None = None,
    ) -> pd.DataFrame:
        del verbose

        if (
            self._arf is None
            or not getattr(self, "is_fitted", False)
        ):
            raise RuntimeError(
                "ARF must be fitted before sample() is called."
            )

        sample_size = (
            self._train_size
            if size is None
            else int(size)
        )

        if sample_size <= 0:
            raise ValueError(
                "size must be greater than zero."
            )

        sample_seed = (
            self.seed
            if seed is None
            else int(seed)
        )

        set_seed(sample_seed)

        synthetic_df = self._arf.forge(
            n=sample_size
        )

        if not isinstance(
            synthetic_df,
            pd.DataFrame,
        ):
            synthetic_df = pd.DataFrame(
                synthetic_df,
                columns=self._columns,
            )

        missing = [
            col
            for col in self._columns
            if col not in synthetic_df.columns
        ]

        if missing:
            raise ValueError(
                f"ARF output is missing columns: {missing}"
            )

        synthetic_df = synthetic_df[
            self._columns
        ].reset_index(drop=True)

        return synthetic_df

    def evaluate(
        self,
        x,
        y,
        model="rf",
    ) -> float:
        """
        Evaluate ARF using Train Synthetic, Test Real (TSTR).

        A classifier is trained on synthetic data generated by ARF
        and evaluated on the supplied real test data.

        Parameters
        ----------
        x:
            Real test feature data.

        y:
            Real test target labels.

        model:
            Evaluation classifier. One of:
            "lr", "rf", or "mlp".

        Returns
        -------
        float:
            Classification accuracy on the real test set.
        """

        if (
            self._arf is None
            or not getattr(self, "is_fitted", False)
        ):
            raise RuntimeError(
                "ARF must be fitted before evaluate() is called."
            )

        # Generate synthetic training data.
        synthetic_df = self.sample(
            size=self._train_size,
            seed=self.seed,
        )

        if self._target_col is None:
            raise RuntimeError(
                "Target column is unavailable."
            )

        x_synth = synthetic_df.drop(
            columns=[self._target_col]
        ).copy()

        y_synth = synthetic_df[
            self._target_col
        ].copy()

        x_test = pd.DataFrame(x).copy()
        y_test = pd.Series(y).copy()

        classifiers = {
            "lr": LogisticRegression(
                max_iter=1000,
                random_state=self.seed,
            ),
            "rf": RandomForestClassifier(
                random_state=self.seed,
            ),
            "mlp": MLPClassifier(
                max_iter=500,
                random_state=self.seed,
            ),
        }

        if isinstance(model, str):
            if model not in classifiers:
                raise ValueError(
                    "model must be one of "
                    "'lr', 'rf', or 'mlp'."
                )

            estimator = classifiers[model]

        elif (
            hasattr(model, "fit")
            and hasattr(model, "predict")
        ):
            estimator = model

        else:
            raise ValueError(
                "Invalid evaluation model."
            )

        categorical_cols = [
            col
            for col in self._categorical_cols
            if col != self._target_col
            and col in x_synth.columns
        ]

        numeric_cols = [
            col
            for col in x_synth.columns
            if col not in categorical_cols
        ]

        preprocessor = ColumnTransformer(
            transformers=[
                (
                    "categorical",
                    OneHotEncoder(
                        handle_unknown="ignore"
                    ),
                    categorical_cols,
                ),
                (
                    "numeric",
                    "passthrough",
                    numeric_cols,
                ),
            ]
        )

        pipeline = Pipeline(
            [
                ("preprocessor", preprocessor),
                ("classifier", estimator),
            ]
        )

        pipeline.fit(
            x_synth,
            y_synth,
        )

        predictions = pipeline.predict(
            x_test
        )

        return accuracy_score(
            y_test,
            predictions,
        )

    def train(
        self,
        dataset,
        size_category="small",
        *args,
        **kwargs,):

        del size_category
        del args

        data_dir = str(dataset)

        categorical_cols = kwargs.pop(
            "categorical_cols",
            None,
        )

        synthetic_dir = kwargs.pop(
            "synthetic_dir",
            None,
        )

        n_synth = kwargs.pop(
            "n_synth",
            None,
        )

        seed = int(
            kwargs.pop(
                "seed",
                self.seed,
            )
        )

        verbose = bool(
            kwargs.pop(
                "verbose",
                self.verbose,
            )
        )

        x_train, y_train = load_split_dataset(
            data_dir
        )

        self.fit(
            x_train,
            y_train,
            categorical_cols=categorical_cols,
            seed=seed,
            verbose=verbose,
        )

        synthetic_df = self.sample(
            len(x_train)
            if n_synth is None
            else int(n_synth),
            seed=seed,
        )

        if synthetic_dir is not None:
            if self._target_col is None:
                raise RuntimeError(
                    "Target column was not recorded during training."
                )

            os.makedirs(
                synthetic_dir,
                exist_ok=True,
            )

            x_synth, y_synth = split_synthetic(
                synthetic_df,
                self._target_col,
            )

            x_synth.to_csv(
                os.path.join(
                    synthetic_dir,
                    "x_synth.csv",
                ),
                index=False,
            )

            y_synth.to_frame().to_csv(
                os.path.join(
                    synthetic_dir,
                    "y_synth.csv",
                ),
                index=False,
            )

        return self
