"""
SynthPop model integration for Katabatic.

Based on:
Nowok, B., Raab, G. M., & Dibben, C. (2016).
synthpop: Bespoke Creation of Synthetic Data in R.
Journal of Statistical Software, 74(11).
https://doi.org/10.18637/jss.v074.i11

This implementation uses the official R package synthpop
and performs sequential conditional synthesis using CART.
"""

import logging
import subprocess
from pathlib import Path

import pandas as pd

from katabatic.models.base_model import Model

from .utils import write_r_script

logger = logging.getLogger(__name__)


class SynthPop(Model):
    """
    Katabatic wrapper for SynthPop (CART-based statistical generator).

    Generates synthetic tabular data by calling the R synthpop package
    via subprocess. Synthesis is performed using CART (Classification
    and Regression Trees) sequentially across all columns.
    """

    def __init__(self, seed: int = 42):
        super().__init__()
        self.seed = seed
        self.synthetic_path = None

    def train(
        self,
        dataset_path: str,
        synthetic_path: str,
        **kwargs,
    ):
        """
        Generate synthetic tabular data using SynthPop.

        Parameters
        ----------
        dataset_path : str
            Path to input CSV containing the training data.
        synthetic_path : str
            Path where synthetic CSV will be saved.
        """
        dataset_path = Path(dataset_path)
        synthetic_path = Path(synthetic_path)
        synthetic_path.parent.mkdir(parents=True, exist_ok=True)

        logger.info("Running SynthPop (CART-based synthesis)")
        logger.info(f"Input dataset   : {dataset_path}")
        logger.info(f"Synthetic output: {synthetic_path}")

        r_script_path = synthetic_path.parent / "run_synthpop.R"

        write_r_script(
            r_script_path=r_script_path,
            input_csv=dataset_path,
            output_csv=synthetic_path,
            seed=self.seed,
        )

        try:
            subprocess.run(
                ["Rscript", str(r_script_path)],
                check=True,
            )
        except subprocess.CalledProcessError as e:
            raise RuntimeError("SynthPop R execution failed") from e

        self.synthetic_path = synthetic_path
        self.is_fitted = True

        logger.info("SynthPop synthetic data generation completed")

        return self

    def sample(self, *args, **kwargs):
        """
        Return the synthetic data generated by SynthPop.
        """
        if not self.is_fitted or self.synthetic_path is None:
            raise RuntimeError("SynthPop must be trained before calling sample().")

        return pd.read_csv(self.synthetic_path)

    def evaluate(self, *args, **kwargs) -> float:
        """
        SynthPop is a synthetic data generator rather than a predictive model.

        Evaluation is performed separately through Katabatic's TSTR
        benchmarking pipeline.
        """
        raise NotImplementedError(
            "SynthPop evaluation is performed through the TSTR benchmarking pipeline."
        )
